language: minimal

services:
    - docker

env:
    global:
        - CONTMETA_html2x="donnellans/html2x" Dir_html2x="${TRAVIS_BUILD_DIR}/html2x" CONTLOCAL_html2x="test-html2x"
        - CONTMETA_logo="donnellans/logo" Dir_logo="${TRAVIS_BUILD_DIR}/logo" CONTLOCAL_logo="test-logo"

before_install:
    - sudo apt-get update && sudo apt-get install -y libseccomp2
    - docker pull debian:stable-slim
    - docker build -f "${Dir_html2x}/Dockerfile" -t ${CONTMETA_html2x} ${Dir_html2x}
    - docker build -f "${Dir_logo}/Dockerfile" -t ${CONTMETA_logo} ${Dir_logo}

script:
    - docker run --name "${CONTLOCAL_html2x}" ${CONTMETA_html2x}
    - docker run --name "${CONTLOCAL_logo}" -v"${Dir_logo}":/data ${CONTMETA_logo} 


after_error:
    - docker logs ${CONTLOCAL_html2x}
    - docker logs ${CONTLOCAL_logo}

after_failure:
    - docker logs ${CONTLOCAL_html2x}
    - docker logs ${CONTLOCAL_logo}